# -*- ruby -*-

source 'http://rubygems.org'

ruby '2.4.3'

gem 'rake', '10.5.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'unicorn'

gem 'pry'
gem 'addressable'
gem 'foreman'

gem 'oj'
gem 'oj_mimic_json'

gem 'redis'
gem 'hiredis'

gem 'sidekiq'
gem 'sidekiq-cron'

gem 'librato-metrics'
gem 'librato-rack'

gem 'adtekio_utilities', :github => "adtekio/utilities"

gem 'mechanize'
gem 'rest-client'
gem 'geokit'
gem 'icalendar'

group :development do
  gem 'dotenv'
  gem 'rerun'
end

group :test do
  gem 'rack-test'
  gem 'rr', '1.0.4'
  gem 'shoulda'
  gem 'jasmine'
  gem 'fakeweb'
  gem 'minitest'
end
