require 'rubygems'
require 'bundler'
require 'bundler/setup'

require 'active_support'
require 'active_support/core_ext/object/blank'

if File.exists?(".env")
  require 'dotenv'
  Dotenv.load
end

require_relative 'config/initializers/carrierwave'
require_relative 'config/initializers/database'

Dir[File.join(File.dirname(__FILE__), 'lib', 'tasks','*.rake')].
  each { |f| load f }

task :default => :test
task :environment do
  require_relative 'app.rb'
end
