version: '2'
services:
  redis_consumer:
    image: redis
    ports:
      - "6379"

  stats_consumer:
    build: ../src/consumers.nodejs
    links:
      - redis_consumer
    environment:
      - KAFKA_HOST=kafka:9092
      - REDIS_CONSUMER=redis://redis_consumer:6379?db=11
      - CONSUMER_NAME=stats_collector

  event_counter:
    build: ../src/consumers.nodejs
    links:
      - redis_consumer
    environment:
      - KAFKA_HOST=kafka:9092
      - REDIS_CONSUMER=redis://redis_consumer:6379?db=12
      - CONSUMER_NAME=event_counter

  metadata_counter:
    build: ../src/consumers.nodejs
    links:
      - redis_consumer
    environment:
      - KAFKA_HOST=kafka:9092
      - REDIS_CONSUMER=redis://redis_consumer:6379?db=10
      - CONSUMER_NAME=metadata_counter

networks:
  default:
    external:
      name: thenetwork
