version: '2'
services:
  redis-consumer:
    image: redis
    ports:
      - "6379"
    volumes:
      - redisconsumerdb:/data

  stats-consumer:
    build: ../src/consumers.nodejs
    links:
      - redis-consumer
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
      - REDIS_CONSUMER=redis://redis-consumer:6379?db=11
      - CONSUMER_NAME=stats_collector

  event-counter:
    build: ../src/consumers.nodejs
    links:
      - redis-consumer
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
      - REDIS_CONSUMER=redis://redis-consumer:6379?db=12
      - CONSUMER_NAME=event_counter

  metadata-counter:
    build: ../src/consumers.nodejs
    links:
      - redis-consumer
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
      - REDIS_CONSUMER=redis://redis-consumer:6379?db=10
      - CONSUMER_NAME=metadata_counter

networks:
  default:
    external:
      name: thenetwork

volumes:
  redisconsumerdb:
    external: true
