version: '2'
services:
  ruby-consumers-db:
    image: redis
    ports:
      - "6379"
    volumes:
      - rubyconsumerdb:/data

  consumers-ruby:
    build: ../src/consumers.ruby
    links:
      - ruby-consumers-db
    ports:
      - "$CONSUMERS_RUBY_PORT:$CONSUMERS_RUBY_PORT"
    environment:
      - PORT=$CONSUMERS_RUBY_PORT
      - RACK_ENV=production
      - REDISTOGO_URL=redis://ruby-consumers-db:6379?db=6
      - ACCESS_DOMAINS=pushtech.de,eccrine.io
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - REDIS_POOL_SIZE=25
      - COOKIE_SECRET=lydbrYEvxBxdUBnGa8TPpVaeBuWez5PG
      - ZOOKEEPER_HOST=zookeeper:2181
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
    command: "foreman start web"
    restart: always

  consumers-ruby-worker:
    build: ../src/consumers.ruby
    links:
      - ruby-consumers-db
    environment:
      - REDIS_POOL_SIZE=25
      - RACK_ENV=production
      - REDISTOGO_URL=redis://ruby-consumers-db:6379?db=6
      - PUSHTECH_API_USER=$PUSHTECH_API_USER
      - PUSHTECH_API_PASSWORD=$PUSHTECH_API_PASSWORD
      - PUSHTECH_API_HOST=http://storage:$STORAGE_PORT
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - IMAGE_HOST=http://imageserver:$IMAGE_SERVER_PORT
      - SENDBIRD_API_TOKEN=$SENDBIRD_API_TOKEN
      - ZOOKEEPER_HOST=zookeeper:2181
      - KAFKA_TOPIC=test
      - LIBRATO_TOKEN=$LIBRATO_TOKEN
      - LIBRATO_USER=$LIBRATO_USER
    command: "foreman start worker"
    restart: always

networks:
  default:
    external:
      name: thenetwork

volumes:
  rubyconsumerdb:
    external: true
