version: '2'
services:
  ruby-consumers-db:
    image: redis
    ports:
      - "6379"
    volumes:
      - rubyconsumerdb:/data

  consumers-ruby:
    image: ${IMAGE_NAMESPACE}.consumers.ruby:v1
    links:
      - ruby-consumers-db
    ports:
      - "$CONSUMERS_RUBY_PORT:$CONSUMERS_RUBY_PORT"
    environment:
      - PORT=$CONSUMERS_RUBY_PORT
      - RACK_ENV=production
      - REDISTOGO_URL=redis://ruby-consumers-db:6379?db=6
      - REDIS_POOL_SIZE=25
      - COOKIE_SECRET=lydbrYEvxBxdUBnGa8TPpVaeBuWez5PG
      - ZOOKEEPER_HOST=zookeeper:2181
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - API_USER=$CONSUMER_API_USER
      - API_PASSWORD=$CONSUMER_API_PASSWORD
    command: "foreman start web"
    restart: always

  consumers-ruby-worker:
    image: ${IMAGE_NAMESPACE}.consumers.ruby:v1
    links:
      - ruby-consumers-db
    environment:
      - REDIS_POOL_SIZE=25
      - RACK_ENV=production
      - REDISTOGO_URL=redis://ruby-consumers-db:6379?db=6
      - PUSHTECH_API_USER=$PUSHTECH_API_USER
      - PUSHTECH_API_PASSWORD=$PUSHTECH_API_PASSWORD
      - PUSHTECH_API_HOST=http://storage:$STORAGE_PORT
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - IMAGE_HOST=http://imageserver:$IMAGE_SERVER_PORT
      - SENDBIRD_API_TOKEN=$SENDBIRD_API_TOKEN
      - ZOOKEEPER_HOST=zookeeper:2181
      - KAFKA_TOPIC=test
      - LIBRATO_TOKEN=$LIBRATO_TOKEN
      - LIBRATO_USER=$LIBRATO_USER
    command: "foreman start worker"
    restart: always

networks:
  default:
    external:
      name: thenetwork

volumes:
  rubyconsumerdb:
    external: true
