version: '2'
services:
  pgimgserver:
    image: postgres:9.6.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=nicesecret
    ports:
      - "5432"
    volumes:
      - imgserverdb:/var/lib/postgresql/data

  imageserver:
    image: ${IMAGE_NAMESPACE}.imageserver:v1
    ports:
      - "$IMAGE_SERVER_PORT:$IMAGE_SERVER_PORT"
    command: "/bin/bash -c 'rake docker:pause_for_db      && \
                            rake docker:if_db_is_migrated && \
                            foreman start web'"
    links:
      - pgimgserver
    environment:
      - RACK_ENV=production
      - PORT=$IMAGE_SERVER_PORT
      - DATABASE_URL=postgres://postgres:nicesecret@pgimgserver:5432/imgserver
      - DOCKER_FILE_STORE=/var/lib/imagesrv/store
      - DB_POOL_SIZE=20
      - DB_TIMEOUT_MSEC=5000
      - API_USER=$IMAGESERVER_API_USER
      - API_PASSWORD=$IMAGESERVER_API_PASSWORD
    volumes:
      - imgserverstore:/var/lib/imagesrv/store
    restart: always

  imageserver-migrate-db:
    image: ${IMAGE_NAMESPACE}.imageserver:v1
    command: "/bin/bash -c 'rake docker:pause_for_db               && \
                            rake docker:if_db_not_migrated         && \
                            rake db:create                         && \
                            rake docker:create_postgres_extensions && \
                            rake db:migrate'"
    links:
      - pgimgserver
    environment:
      - RACK_ENV=production
      - DATABASE_URL=postgres://postgres:nicesecret@pgimgserver:5432/imgserver
    restart: "no"

networks:
  default:
    external:
      name: thenetwork

volumes:
  imgserverdb:
    external: true
  imgserverstore:
    external: true
