version: '2'
services:
  kafidx:
    image: ${IMAGE_NAMESPACE}.kafidx:v1
    ports:
      - "$KAFIDX_PORT:$KAFIDX_PORT"
    environment:
      - PORT=$KAFIDX_PORT
      - WEB_CONCURRENCY=3
      - ZOOKEEPER_HOST=zookeeper:2181
      - API_USER=$KAFIDX_USER
      - API_PASSWORD=$KAFIDX_PASSWORD
      - REDIS_URL=redis://redis-consumer:6379?db=

networks:
  default:
    external:
      name: thenetwork
