version: '2'
services:
  kafidx:
    build: ../src/kafidx
    ports:
      - "$KAFIDX_PORT:$KAFIDX_PORT"
    environment:
      - KAFKA_HOST=kafka:9092
      - PORT=$KAFIDX_PORT
      - WEB_CONCURRENCY=3

networks:
  default:
    external:
      name: thenetwork
