version: '2'
services:
  kafidx:
    image: ${IMAGE_NAMESPACE}.kafidx:v1
    ports:
      - "$KAFIDX_PORT:$KAFIDX_PORT"
    environment:
      - PORT=$KAFIDX_PORT
      - WEB_CONCURRENCY=3
      - ZOOKEEPER_HOST=zookeeper:2181

networks:
  default:
    external:
      name: thenetwork
