version: '2'
services:
  kafkastore:
    build: ../src/kafkastore
    environment:
      - REDIS_TRACKING=redis://redis_tracker:6379?db=6
      - ZOOKEEPER_HOST=zookeeper:2181

networks:
  default:
    external:
      name: thenetwork
