version: '2'
services:
  kafkastore:
    image: ${IMAGE_NAMESPACE}.kafkastore:v1
    environment:
      - REDIS_TRACKING=redis://redis-tracker:6379?db=6
      - ZOOKEEPER_HOST=zookeeper:2181
    restart: always

networks:
  default:
    external:
      name: thenetwork
