version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.11
    environment:
      - ZOO_MAX_CLIENT_CNXNS=600
    ports:
      - "2181"
    restart: always
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092"
    hostname: kafka
    links:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
    restart: always

networks:
  default:
    external:
      name: thenetwork
