version: '2'
services:
  redis-offerserver:
    image: redis
    ports:
      - "6379"
    volumes:
      - offerserverdb:/data

  offerserver:
    image: ${IMAGE_NAMESPACE}.offerserver:v1
    links:
      - redis-offerserver
    ports:
      - "$OFFERSERVER_PORT:$OFFERSERVER_PORT"
    environment:
      - RACK_ENV=production
      - REDISTOGO_URL=redis://redis-offerserver:6379?db=6
      - PORT=$OFFERSERVER_PORT
      - COOKIE_SECRET=$OFFERSERVER_COOKIE_SECRET
      - REDIS_POOL_SIZE=20
      - API_USER=$OFFERSERVER_API_USER
      - API_PASSWORD=$OFFERSERVER_API_PASSWORD
    command: "foreman start web"
    restart: always

  offerserver-worker:
    image: ${IMAGE_NAMESPACE}.offerserver:v1
    links:
      - redis-offerserver
    environment:
      - REDIS_POOL_SIZE=20
      - RACK_ENV=production
      - REDISTOGO_URL=redis://redis-offerserver:6379?db=6
      - PUSHTECH_API_USER=$PUSHTECH_API_USER
      - PUSHTECH_API_PASSWORD=$PUSHTECH_API_PASSWORD
      - PUSHTECH_API_HOST=http://storage:$STORAGE_PORT
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - IMAGE_HOST=http://imageserver:$IMAGE_SERVER_PORT
      - IMAGE_API_USER=$IMAGESERVER_API_USER
      - IMAGE_API_PASSWORD=$IMAGESERVER_API_PASSWORD
    command: "foreman start worker"
    restart: always

networks:
  default:
    external:
      name: thenetwork

volumes:
  offerserverdb:
    external: true
