version: '2'
services:
  mongo_store:
    image: mongo:2.6
    ports:
      - "27017"
    volumes:
      - mongostoredb:/data/db

  storage:
    build: ../src/storage
    links:
      - mongo_store
    ports:
      - "$STORAGE_PORT:$STORAGE_PORT"
    environment:
      - PORT=$STORAGE_PORT
      - IMAGE_HOST=https://assets.pushtech.de
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - NOTIFY_HOST=https://notify.pushtech.de
      - MONGOHQ_URL=mongodb://mongo_store:27017/store
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - WEB_CONCURRENCY=8
      - COOKIE_SECRET=X1n4zsExsKtngfv4HqGGIz6bZoL5YIvo
    restart: always

networks:
  default:
    external:
      name: thenetwork

volumes:
  mongostoredb:
    external: true
