version: '2'
services:
  mongo-store:
    image: mongo:2.6
    ports:
      - "27017"
    volumes:
      - mongostoredb:/data/db

  storage:
    image: ${IMAGE_NAMESPACE}.storage:v1
    links:
      - mongo-store
    ports:
      - "$STORAGE_PORT:$STORAGE_PORT"
    environment:
      - PORT=$STORAGE_PORT
      - IMAGE_HOST=http://imageserver:$IMAGE_SERVER_PORT
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - NOTIFY_HOST=https://notify.pushtech.de
      - NOTIFY_API_USER=$NOTIFICATION_API_USER
      - NOTIFY_API_PASSWORD=$NOTIFICATION_API_PASSWORD
      - MONGOHQ_URL=mongodb://mongo-store:27017/store
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - WEB_CONCURRENCY=8
      - COOKIE_SECRET=X1n4zsExsKtngfv4HqGGIz6bZoL5YIvo
      - API_USER=$PUSHTECH_API_USER
      - API_PASSWORD=$PUSHTECH_API_PASSWORD
    restart: always

networks:
  default:
    external:
      name: thenetwork

volumes:
  mongostoredb:
    external: true
