version: '2'
services:
  redis-tracker:
    image: redis
    ports:
      - "6379"
    volumes:
      - trackerdb:/data

  tracker:
    image: ${IMAGE_NAMESPACE}.tracker:v1
    links:
      - redis-tracker
    ports:
      - "$TRACKER_PORT:$TRACKER_PORT"
    environment:
      - REDIS_URL=redis://redis-tracker:6379?db=6
      - PORT=$TRACKER_PORT

networks:
  default:
    external:
      name: thenetwork

volumes:
  trackerdb:
    external: true
