version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379"
  tracker:
    build: ../src/tracker
    links:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379?db=6
      - PORT=5000

networks:
  default:
    external:
      name: thenetwork
