version: '2'
services:
  redis_tracker:
    image: redis
    ports:
      - "6379"
  tracker:
    build: ../src/tracker
    links:
      - redis_tracker
    ports:
      - "$TRACKER_PORT:$TRACKER_PORT"
    environment:
      - REDIS_URL=redis://redis_tracker:6379?db=6
      - PORT=$TRACKER_PORT

networks:
  default:
    external:
      name: thenetwork
