version: '2'
services:
  pgwebsite:
    image: postgres:9.6.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=nicesecret
    ports:
      - "5432"
    volumes:
      - websitedb:/var/lib/postgresql/data

  website:
    image: ${IMAGE_NAMESPACE}.website:v1
    ports:
      - "$WEBSITE_PORT:$WEBSITE_PORT"
    command: "/bin/bash -c 'rake docker:pause_for_db      && \
                            rake docker:if_db_is_migrated && \
                            foreman start web'"
    links:
      - pgwebsite
    environment:
      - RACK_ENV=production
      - PORT=$WEBSITE_PORT
      - DATABASE_URL=postgres://postgres:nicesecret@pgwebsite:5432/webs
      - ASSETS_HOST=http://imageserver:$IMAGE_SERVER_PORT
      - ASSETS_API_USER=$IMAGESERVER_API_USER
      - ASSETS_API_PASSWORD=$IMAGESERVER_API_PASSWORD
      - EXTERNAL_ASSETS_HOST=http://localhost:$IMAGE_SERVER_PORT
      - PROFILE_HOST=https://profile.pushtech.de
      - LOGIN_HOST=website:$WEBSITE_PORT
      - NOTIFIER_HOST=http://notificationserver:$NOTIFICATION_SERVER_PORT
      - NOTIFIER_API_USER=$NOTIFICATION_API_USER
      - NOTIFIER_API_PASSWORD=$NOTIFICATION_API_PASSWORD
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - MANDRILL_API_KEY=$MANDRILL_API_KEY
      - PUSHTECH_API_USER=$PUSHTECH_API_USER
      - PUSHTECH_API_PASSWORD=$PUSHTECH_API_PASSWORD
      - PUSHTECH_API_HOST=http://storage:$STORAGE_PORT
      - SENDBIRD_API_TOKEN=$SENDBIRD_API_TOKEN
      - SENDBIRD_API_ID=$SENDBIRD_API_ID
      - TRACKER_HOST=http://tracker:$TRACKER_PORT
      - DB_POOL_SIZE=20
      - DB_TIMEOUT_MSEC=5000
      - COOKIE_SECRET=$WEBSITE_COOKIE_SECRET
      - PASSWORD_PEPPER=$WEBSITE_PASSWORD_PEPPER
      - CRED_KEY_BASE64=$WEBSITE_CRED_KEY_BASE64
      - CRED_IV_BASE64=$WEBSITE_CRED_IV_BASE64
      - RSA_PRIVATE_KEY_BASE64=$WEBSITE_RSA_PRIVATE_KEY_BASE64
      - RSA_PUBLIC_KEY_BASE64=$WEBSITE_RSA_PUBLIC_KEY_BASE64
    restart: always

  website-migrate-db:
    image: ${IMAGE_NAMESPACE}.website:v1
    command: "/bin/bash -c 'rake docker:pause_for_db               && \
                            rake docker:if_db_not_migrated         && \
                            rake db:create                         && \
                            rake docker:create_postgres_extensions && \
                            rake db:migrate'"
    links:
      - pgwebsite
    environment:
      - RACK_ENV=production
      - DATABASE_URL=postgres://postgres:nicesecret@pgwebsite:5432/webs
    restart: "no"

networks:
  default:
    external:
      name: thenetwork

volumes:
  websitedb:
    external: true
