---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: consumers-ruby
  name: consumers-ruby
spec:
  type: LoadBalancer
  ports:
  - port: 5051
    targetPort: 5051
    nodePort: 30351
  selector:
    io.kompose.service: consumers-ruby

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consumers-ruby
  name: consumers-ruby
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: consumers-ruby
    spec:
      restartPolicy: Always
      containers:
      - args:
        - foreman
        - start
        - web
        env:
        - name: COOKIE_SECRET
          value: lydbrYEvxBxdUBnGa8TPpVaeBuWez5PG
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: CONSUMERS_RUBY_PORT
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://consumers-ruby-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "25"
        - name: TRACKER_HOST
          value: http://tracker:5222
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_ENDPOINT
        image: pushtech.consumers.ruby:v1
        name: consumers-ruby
        ports:
        - containerPort: 5051
        resources: {}
