---
apiVersion: v1
kind: Service
metadata:
  annotations:
    subdomain.name: kafidx
  labels:
    io.kompose.service: kafidx
  name: kafidx
spec:
  type: LoadBalancer
  ports:
  - port: 5031
    targetPort: 5031
    nodePort: 30331
  selector:
    io.kompose.service: kafidx
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafidx
  name: kafidx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafidx
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: pushtech.kafidx:v1
        name: kafidx
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: KAFIDX_PORT
        - name: WEB_CONCURRENCY
          value: "3"
        - name: WEB_SOCKET_SCHEMA
          valueFrom:
            secretKeyRef:
              name: extcfg
              key: WEB_SOCKET_SCHEMA
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_HOST
        - name: API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: KAFIDX_USER
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: KAFIDX_PASSWORD
        ports:
        - containerPort: 5031
        resources: {}
