---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka
  name: kafkasrv
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: kafka
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      initContainers:
        - name: wait-on-zookeeper-service
          image: busybox
          env:
            - name: ZK_HOST_PORT
              valueFrom:
                secretKeyRef:
                  name: k8scfg
                  key: ZOOKEEPER_HOST
          command:
            - /bin/sh
            - -c
            - ZKHOST=${ZK_HOST_PORT/:2181/} ; until nslookup $ZKHOST; do echo waiting for zookeeper - $ZKHOST; sleep 2; done;
      containers:
        - image: wurstmeister/kafka:0.10.2.0
          name: kafka
          resources:
            requests:
              memory: "700Mi"
              cpu: "400m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CREATE_TOPICS
              value: test:1:1
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: k8scfg
                  key: ZOOKEEPER_HOST
              # Can't use BROKER_ID_COMMAND since we're using 0.10.0 branch
              # see --> https://github.com/wurstmeister/kafka-docker/blob/0.10.0/start-kafka.sh
            - name: CUSTOM_INIT_SCRIPT
              value: "KAFKA_BROKER_ID=$(ifconfig | grep \"inet addr\" | grep -v 127.0.0.1 | awk '// {sub(\"addr:\",\"\",$2); split($2,ary,\"[.]\"); sum=0; for(idx=1;idx<5;idx++){sum+=ary[idx]}; print (sum % 1000);}') ; echo \"broker.id=$KAFKA_BROKER_ID\" >> $KAFKA_HOME/config/server.properties"
