---
apiVersion: v1
kind: Service
metadata:
  annotations:
    subdomain.name: offers
  labels:
    io.kompose.service: offerserver
  name: offerserver
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30341
  selector:
    io.kompose.service: offerserver
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: offerserver
  name: offerserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: offerserver
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - name: offerserver
        image: pushtech.offerserver:v1
        args:
        - foreman
        - start
        - web
        resources:
          requests:
            memory: "200Mi"
            cpu: "40m"
          limits:
            memory: "400Mi"
            cpu: "60m"
        env:
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: OFFERSERVER_COOKIE_SECRET
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: OFFERSERVER_PORT
        - name: WEB_CONCURRENCY
          value: "5"
        - name: WEB_TIMEOUT
          value: "15"
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://offerserver-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "20"
        - name: API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: OFFERSERVER_API_USER
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: OFFERSERVER_API_PASSWORD
        ports:
        - containerPort: 5000
