---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: storage
  name: storage
spec:
  type: LoadBalancer
  ports:
  - port: 5011
    targetPort: 5011
    nodePort: 30321
  selector:
    io.kompose.service: storage
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      restartPolicy: Always
      containers:
      - env:
        - name: COOKIE_SECRET
          value: X1n4zsExsKtngfv4HqGGIz6bZoL5YIvo
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_API_KEY
        - name: IMAGE_HOST
          value: http://imageserver:5061
        - name: MONGOHQ_URL
          value: mongodb://storage-db:27017/store
        - name: NOTIFY_HOST
          value: https://notify.pushtech.de
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: STORAGE_PORT
        - name: TRACKER_HOST
          value: http://tracker:5222
        - name: WEB_CONCURRENCY
          value: "8"
        image: pushtech.storage:v1
        name: storage
        ports:
        - containerPort: 5011
        resources: {}
