---
apiVersion: v1
kind: Service
metadata:
  annotations:
    subdomain.name: trk
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  type: LoadBalancer
  ports:
  - port: 5222
    targetPort: 5222
    nodePort: 30222
  selector:
    io.kompose.service: tracker

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tracker
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: redis
        name: redis-tracker
        ports:
        - containerPort: 6379
        resources: {}
      - image: pushtech.tracker:v1
        name: tracker
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: envsecrets
                key: TRACKER_PORT
          - name: REDIS_URL
            value: redis://localhost:6379?db=6
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: envsecrets
                key: TRACKER_COOKIE_SECRET
        ports:
        - containerPort: 5222
      - image: pushtech.kafkastore:v1
        name: kafkastore
        env:
          - name: REDIS_TRACKING
            value: redis://localhost:6379?db=6
          - name: ZOOKEEPER_HOST
            valueFrom:
              secretKeyRef:
                name: k8scfg
                key: ZOOKEEPER_HOST
