---
apiVersion: v1
kind: Service
metadata:
  annotations:
    subdomain.name: www
  labels:
    io.kompose.service: website
  name: website
spec:
  type: LoadBalancer
  ports:
  - port: 5123
    targetPort: 5123
    nodePort: 30223
  selector:
    provide.service: website

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        provide.service: website
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      initContainers:
      - image: pushtech.website:v1
        name: website-migrate-db
        args:
        - /bin/bash
        - -c
        - (rake docker:pause_for_db               &&
           rake docker:if_db_not_migrated         &&
           rake db:create                         &&
           rake docker:create_postgres_extensions &&
           rake db:migrate) ; exit 0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: WEBSITE_DB_URL
        - name: RACK_ENV
          value: production
      containers:
      - image: pushtech.website:v1
        name: website
        args:
        - /bin/bash
        - -c
        - rake docker:pause_for_db      &&
          rake docker:if_db_is_migrated &&
          foreman start web
        resources:
          requests:
            memory: "200Mi"
            cpu: "40m"
          limits:
            memory: "400Mi"
            cpu: "80m"
        env:
        - name: DB_POOL_SIZE
          value: "20"
        - name: DB_TIMEOUT_MSEC
          value: "5000"
        - name: RACK_ENV
          value: production
        - name: ASSETS_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: IMAGE_HOST
        - name: ASSETS_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_USER
        - name: ASSETS_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_PASSWORD
        - name: EXTERNAL_ASSETS_HOST
          valueFrom:
            secretKeyRef:
              name: extcfg
              key: ASSETS_HOST
        - name: CDN_HOSTS
          valueFrom:
            secretKeyRef:
              name: extcfg
              key: WEBSITE_CDN_HOSTS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: WEBSITE_DB_URL
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_API_KEY
        - name: LOGIN_HOST
          valueFrom:
            secretKeyRef:
              name: extcfg
              key: LOGIN_HOST
        - name: MANDRILL_API_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: MANDRILL_API_KEY
        - name: NOTIFIER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFY_HOST
        - name: NOTIFIER_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: NOTIFICATION_API_USER
        - name: NOTIFIER_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: NOTIFICATION_API_PASSWORD
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_PORT
        - name: PROFILE_HOST
          valueFrom:
            secretKeyRef:
              name: extcfg
              key: PROFILE_HOST
        - name: PUSHTECH_API_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: PUSHTECH_API_HOST
        - name: PUSHTECH_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_USER
        - name: PUSHTECH_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_PASSWORD
        - name: SENDBIRD_API_ID
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_ID
        - name: SENDBIRD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_TOKEN
        - name: TRACKER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: TRACKER_HOST
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_COOKIE_SECRET
        - name: PASSWORD_PEPPER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_PASSWORD_PEPPER
        - name: CRED_KEY_BASE64
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_CRED_KEY_BASE64
        - name: CRED_IV_BASE64
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_CRED_IV_BASE64
        - name: RSA_PRIVATE_KEY_BASE64
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_RSA_PRIVATE_KEY_BASE64
        - name: RSA_PUBLIC_KEY_BASE64
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: WEBSITE_RSA_PUBLIC_KEY_BASE64
        ports:
        - containerPort: 5123
