---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: zookeeper
    spec:
      imagePullSecrets:
      - name: meatdocker
      containers:
      - image: zookeeper:3.4.11
        name: zookeeper
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "400Mi"
            cpu: "600m"
        env:
        - name: ZOO_MAX_CLIENT_CNXNS
          value: "600"
        ports:
        - containerPort: 2181
      restartPolicy: Always
