apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/consumers.ruby.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: consumers-ruby
  name: consumers-ruby
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consumers-ruby
    spec:
      containers:
      - args:
        - foreman
        - start
        - web
        env:
        - name: ACCESS_DOMAINS
          value: pushtech.de,eccrine.io
        - name: COOKIE_SECRET
          value: lydbrYEvxBxdUBnGa8TPpVaeBuWez5PG
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_CLIENT_SECRET
        - name: PORT
          value: "5051"
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://ruby-consumers-db:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "25"
        - name: TRACKER_HOST
          value: http://tracker:5222
        - name: ZOOKEEPER_HOST
          value: zookeeper:2181
        image: pushtech.consumers.ruby:v1
        name: consumers-ruby
        ports:
        - containerPort: 5051
        resources: {}
      restartPolicy: Always
status: {}
