apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/consumers.ruby.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: consumers-ruby
  name: consumers-ruby
spec:
  ports:
  - name: "5051"
    port: 5051
    targetPort: 5051
  selector:
    io.kompose.service: consumers-ruby
status:
  loadBalancer: {}
