apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/consumers.nodejs.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: event-counter
  name: event-counter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: event-counter
    spec:
      containers:
      - env:
        - name: CONSUMER_NAME
          value: event_counter
        - name: REDIS_CONSUMER
          value: redis://redis-consumer:6379?db=12
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_ENDPOINT
        image: pushtech.consumers.nodejs:v1
        name: event-counter
        resources: {}
      restartPolicy: Always
status: {}
