apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/imageserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: imageserver
  name: imageserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: imageserver
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - rake docker:pause_for_db      && rake docker:if_db_is_migrated && foreman
          start web
        env:
        - name: DATABASE_URL
          value: postgres://postgres:nicesecret@pgimgserver:5432/imgserver
        - name: DB_POOL_SIZE
          value: "20"
        - name: DB_TIMEOUT_MSEC
          value: "5000"
        - name: DOCKER_FILE_STORE
          value: /var/lib/imagesrv/store
        - name: PORT
          value: "5061"
        - name: RACK_ENV
          value: production
        image: pushtech.imageserver:v1
        name: imageserver
        ports:
        - containerPort: 5061
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/imagesrv/store
          name: imgserverstore
      restartPolicy: Always
      volumes:
      - name: imgserverstore
        persistentVolumeClaim:
          claimName: imgserverstore
status: {}
