---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/kafka-zookeeper.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafkasrv
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/kafka-zookeeper.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-on-zookeeper-service
          image: busybox
          command: ['sh', '-c', 'until nslookup zookeeper.pushtech.svc.cluster.local; do echo waiting for zookeeper; sleep 2; done;']
      containers:
        - image: wurstmeister/kafka:0.10.2.0
          name: kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CREATE_TOPICS
              value: test:1:1
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: k8scfg
                  key: ZOOKEEPER_ENDPOINT
              # Can't use BROKER_ID_COMMAND since we're using 0.10.0 branch
              # see --> https://github.com/wurstmeister/kafka-docker/blob/0.10.0/start-kafka.sh
            - name: CUSTOM_INIT_SCRIPT
              value: "KAFKA_BROKER_ID=$(ifconfig | grep \"inet addr\" | grep -v 127.0.0.1 | awk '// {sub(\"addr:\",\"\",$2); gsub(\"[.]\",\"\",$2); print substr($2,5,3);}') ; echo \"broker.id=$KAFKA_BROKER_ID\" >> $KAFKA_HOME/config/server.properties"
