apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/storage.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-store
  name: mongo-store
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-store
    spec:
      containers:
      - image: mongo:2.6
        name: mongo-store
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongostoredb
      restartPolicy: Always
      volumes:
      - name: mongostoredb
        persistentVolumeClaim:
          claimName: mongostoredb
status: {}
