---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: notificationserver
  name: notificationserver
spec:
  type: LoadBalancer
  ports:
  - port: 5041
    targetPort: 5041
    nodePort: 30241
  selector:
    io.kompose.service: notificationserver
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: notificationserver
  name: notificationserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: notificationserver
    spec:
      restartPolicy: Always
      initContainers:
      - args:
        - /bin/bash
        - -c
        - (rake docker:pause_for_postgres         &&
           rake docker:if_db_not_migrated         &&
           rake db:create                         &&
           rake docker:create_postgres_extensions &&
           rake db:migrate ) ; exit 0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFSERVER_DB_URL
        - name: RACK_ENV
          value: production
        image: pushtech.notificationserver:v1
        name: notserver-migrate-db

      containers:
      - args:
        - /bin/bash
        - -c
        - rake docker:pause_for_postgres &&
          rake docker:pause_for_redis    &&
          rake docker:if_db_is_migrated  &&
          foreman start web
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFSERVER_DB_URL
        - name: DB_POOL_SIZE
          value: "20"
        - name: DB_TIMEOUT_MSEC
          value: "5000"
        - name: ONESIGNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: ONESIGNAL_API_KEY
        - name: ONESIGNAL_APP_ID
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: ONESIGNAL_APP_ID
        - name: ONESIGNAL_USER_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: ONESIGNAL_USER_AUTH_KEY
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: NOTIFICATION_SERVER_PORT
        - name: PUSHTECH_API_HOST
          value: http://storage:5011
        - name: RACK_ENV
          value: production
        - name: RATE_LIMIT_SECONDS
          value: "300"
        - name: REDISTOGO_URL
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFSERVER_REDIS_URL
        - name: SENDBIRD_API_ID
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_ID
        - name: SENDBIRD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_TOKEN
        - name: TRACKER_HOST
          value: http://tracker:5222
        - name: WEB_TIMEOUT
          value: "30"
        image: pushtech.notificationserver:v1
        name: notificationserver
        ports:
        - containerPort: 5041
        resources: {}
