apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/offerserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: offerserver
  name: offerserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: offerserver
    spec:
      containers:
      - args:
        - foreman
        - start
        - web
        env:
        - name: ACCESS_DOMAINS
          value: pushtech.de,eccrine.io
        - name: COOKIE_SECRET
          value: x7kGp9ci24xugSNTnn9sVajQnoKmFhEx
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: GOOGLE_CLIENT_SECRET
        - name: PORT
          value: "5000"
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://redis-offerserver:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "20"
        image: pushtech.offerserver:v1
        name: offerserver
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
