apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/website.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pgwebsite
  name: pgwebsite
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgwebsite
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: nicesecret
        image: postgres:9.6.6
        name: pgwebsite
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: websitedb
      restartPolicy: Always
      volumes:
      - name: websitedb
        persistentVolumeClaim:
          claimName: websitedb
status: {}
