apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/offerserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-offerserver
  name: redis-offerserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-offerserver
    spec:
      containers:
      - image: redis
        name: redis-offerserver
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: offerserverdb
      restartPolicy: Always
      volumes:
      - name: offerserverdb
        persistentVolumeClaim:
          claimName: offerserverdb
status: {}
