apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/notificationserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redisnotserver
  name: redisnotserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redisnotserver
    spec:
      containers:
      - image: redis
        name: redisnotserver
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: notserverredisdb
      restartPolicy: Always
      volumes:
      - name: notserverredisdb
        persistentVolumeClaim:
          claimName: notserverredisdb
status: {}
