apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/tracker.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-tracker
  name: redis-tracker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-tracker
    spec:
      containers:
      - image: redis
        name: redis-tracker
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: trackerdb
      restartPolicy: Always
      volumes:
      - name: trackerdb
        persistentVolumeClaim:
          claimName: trackerdb
status: {}
