apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/consumers.nodejs.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-consumer
  name: redis-consumer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-consumer
    spec:
      containers:
      - image: redis
        name: redis-consumer
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redisconsumerdb
      restartPolicy: Always
      volumes:
      - name: redisconsumerdb
        persistentVolumeClaim:
          claimName: redisconsumerdb
status: {}
