apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/storage.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  ports:
  - name: "5011"
    port: 5011
    targetPort: 5011
  selector:
    io.kompose.service: storage
status:
  loadBalancer: {}
