---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/tracker.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  type: LoadBalancer
  ports:
  - name: "5222"
    port: 5222
    targetPort: 5222
    nodePort: 30222
  selector:
    io.kompose.service: tracker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: trackerdb
  name: trackerdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-tracker
    spec:
      restartPolicy: Always
      volumes:
      - name: trackerdb
        persistentVolumeClaim:
          claimName: trackerdb
      containers:
      - image: redis
        name: redis-tracker
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: trackerdb
      - image: pushtech.tracker:v1
        name: tracker
        env:
          - name: PORT
            value: "5222"
          - name: REDIS_URL
            value: redis://localhost:6379?db=6
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 5222
      - image: pushtech.kafkastore:v1
        name: kafkastore
        env:
          - name: REDIS_TRACKING
            value: redis://localhost:6379?db=6
          - name: ZOOKEEPER_HOST
            value: zookeeper.pushtech.svc.cluster.local:2181
