apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/tracker.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tracker
    spec:
      containers:
      - env:
        - name: PORT
          value: "5222"
        - name: REDIS_URL
          value: redis://redis-tracker:6379?db=6
        image: pushtech.tracker:v1
        name: tracker
        ports:
        - containerPort: 5222
        resources: {}
      restartPolicy: Always
status: {}
