apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/tracker.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tracker
  name: tracker
spec:
  ports:
  - name: "5222"
    port: 5222
    targetPort: 5222
  selector:
    io.kompose.service: tracker
status:
  loadBalancer: {}
