apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/website.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: website
  name: website
spec:
  ports:
  - name: "5123"
    port: 5123
    targetPort: 5123
  selector:
    io.kompose.service: website
status:
  loadBalancer: {}
