apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stats-consumer
  name: consumers-nodejs-stats-consumer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: stats-consumer
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: pushtech.consumers.nodejs:v1
        name: stats-consumer
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "30m"
        env:
        - name: CONSUMER_NAME
          value: stats_collector
        - name: REDIS_CONSUMER
          value: redis://consumers-nodejs-redis:6379?db=11
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_HOST
