apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: metadata-counter
  name: consumers-nodejs-metadata-counter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: metadata-counter
    spec:
      containers:
      - env:
        - name: CONSUMER_NAME
          value: metadata_counter
        - name: REDIS_CONSUMER
          value: redis://consumers-nodejs-redis:6379?db=10
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_HOST
        image: pushtech.consumers.nodejs:v1
        name: metadata-counter
        resources: {}
      restartPolicy: Always
