apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consumers-ruby-worker
  name: consumers-ruby-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: consumers-ruby-worker
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: pushtech.consumers.ruby:v1
        name: consumers-ruby-worker
        args:
        - foreman
        - start
        - worker
        resources:
          requests:
            memory: "200Mi"
            cpu: "15m"
          limits:
            memory: "400Mi"
            cpu: "40m"
        env:
        - name: IMAGE_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: IMAGE_HOST
        - name: IMAGE_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_USER
        - name: IMAGE_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_PASSWORD
        - name: KAFKA_TOPIC
          value: test
        - name: LIBRATO_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: LIBRATO_TOKEN
        - name: LIBRATO_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: LIBRATO_USER
        - name: PUSHTECH_API_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: PUSHTECH_API_HOST
        - name: PUSHTECH_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_PASSWORD
        - name: PUSHTECH_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_USER
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://consumers-ruby-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "25"
        - name: SENDBIRD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_TOKEN
        - name: TRACKER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: TRACKER_HOST
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_HOST
