apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: event-counter
  name: consumers-nodejs-event-counter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: event-counter
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: pushtech.consumers.nodejs:v1
        name: event-counter
        env:
        - name: CONSUMER_NAME
          value: event_counter
        - name: REDIS_CONSUMER
          value: redis://consumers-nodejs-redis:6379?db=12
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_HOST
