apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consumers-ruby-worker
  name: consumers-ruby-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: consumers-ruby-worker
    spec:
      restartPolicy: Always
      containers:
      - args:
        - foreman
        - start
        - worker
        env:
        - name: IMAGE_HOST
          value: http://imageserver:5061
        - name: KAFKA_TOPIC
          value: test
        - name: LIBRATO_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: LIBRATO_TOKEN
        - name: LIBRATO_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: LIBRATO_USER
        - name: PUSHTECH_API_HOST
          value: http://storage:5011
        - name: PUSHTECH_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_PASSWORD
        - name: PUSHTECH_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_USER
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://consumers-ruby-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "25"
        - name: SENDBIRD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: SENDBIRD_API_TOKEN
        - name: TRACKER_HOST
          value: http://tracker:5222
        - name: ZOOKEEPER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: ZOOKEEPER_ENDPOINT
        image: pushtech.consumers.ruby:v1
        name: consumers-ruby-worker
        resources: {}
