apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/offerserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: offerserver-worker
  name: offerserver-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: offerserver-worker
    spec:
      containers:
      - args:
        - foreman
        - start
        - worker
        env:
        - name: CAR2GO_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: CAR2GO_CONSUMER_KEY
        - name: CARJUMP_SECRET
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: CARJUMP_SECRET
        - name: IMAGE_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: IMAGE_HOST
        - name: PUSHTECH_API_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: PUSHTECH_API_HOST
        - name: PUSHTECH_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_PASSWORD
        - name: PUSHTECH_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_USER
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://offerserver-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "20"
        - name: TRACKER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: TRACKER_HOST
        image: pushtech.offerserver:v1
        name: offerserver-worker
        resources: {}
      restartPolicy: Always
