apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: offerserver-worker
  name: offerserver-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: offerserver-worker
    spec:
      imagePullSecrets:
      - name: meatdocker
      restartPolicy: Always
      containers:
      - image: pushtech.offerserver:v1
        name: offerserver-worker
        args:
        - foreman
        - start
        - worker
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "1500Mi"
            cpu: "800m"
        env:
        - name: IMAGE_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: IMAGE_HOST
        - name: IMAGE_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_USER
        - name: IMAGE_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: IMAGESERVER_API_PASSWORD
        - name: PUSHTECH_API_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: PUSHTECH_API_HOST
        - name: PUSHTECH_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_PASSWORD
        - name: PUSHTECH_API_USER
          valueFrom:
            secretKeyRef:
              name: envsecrets
              key: PUSHTECH_API_USER
        - name: RACK_ENV
          value: production
        - name: REDISTOGO_URL
          value: redis://offerserver-redis:6379?db=6
        - name: REDIS_POOL_SIZE
          value: "20"
        - name: TRACKER_HOST
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: TRACKER_HOST
