---
apiVersion: v1
kind: Service
metadata:
  name: redisconsumer
  labels:
    name: redisconsumer
  namespace: pushtech
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-consumer
