---
apiVersion: v1
kind: Service
metadata:
  name: redistsrv
  labels:
    name: redistsrv
  namespace: pushtech
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-tracker
