---
apiVersion: v1
kind: Service
metadata:
  name: trackersrv
  labels:
    name: trackersrv
  namespace: pushtech
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30322
  selector:
    name: tracker
