---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tracker
  labels:
    name: tracker
  namespace: pushtech
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tracker
    spec:
      containers:
        - name: tracker
          image: pushtech.tracker:v1
          env:
            - name: REDIS_URL
              value: redis://redistsrv.pushtech.svc.cluster.local:6379?db=6
          ports:
            - name: tracker
              containerPort: 5000
