# -*- ruby -*-
source 'http://rubygems.org'

ruby '2.4.3'

gem 'rake', '10.5.0'

gem 'pry'
gem 'json'
gem 'i18n'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-support'
gem 'haml'
gem 'foreman'
gem 'unicorn'

gem 'activerecord'
gem 'active_record_migrations'
gem 'activerecord-postgis-adapter'
gem 'pg'
gem 'activerecord-import'

gem 'mechanize'
gem 'launchy'

gem 'adtekio_utilities', :github => "adtekio/utilities"
gem 'jwe'
gem 'mailchimp'
gem 'one_signal'

gem 'redis'
gem 'hiredis'
gem 'connection_pool'
gem 'rest-client'

group :development do
  gem 'html2haml'
  gem 'dotenv', :github => 'gorenje/dotenv', :branch => 'squaure_brackets'
  gem 'sass'
  gem 'rerun'
  gem 'term-ansicolor'
end

group :test do
  gem 'rack-test'
  gem 'rr', '1.0.4'
  gem 'shoulda'
  gem 'jasmine'
  gem 'fakeweb'
  gem 'minitest'
end
