---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis-consumer
  name: consumers-nodejs-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-consumer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis-consumer
  name: redis-consumer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis-consumer
    spec:
      restartPolicy: Always
      volumes:
      - name: redisconsumerdb
        persistentVolumeClaim:
          claimName: redisconsumerdb
      containers:
      - image: redis
        name: redis-consumer
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redisconsumerdb
