---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pgimgserver
  name: imgserver-db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: pgimgserver

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pgimgserver
  name: imgserver-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pgimgserver
    spec:
      restartPolicy: Always
      volumes:
      - name: imgserverdb
        persistentVolumeClaim:
          claimName: imgserverdb
      containers:
      - image: postgres:9.6.6
        name: pgimgserver
        resources:
          requests:
            memory: "80Mi"
            cpu: "20m"
          limits:
            memory: "200Mi"
            cpu: "50m"
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: IMGSERVER_PG_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: imgserverdb
