---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pgnotserver
  name: notifserver-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: pgnotserver

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose/notificationserver.yml
    kompose.version: 1.5.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: pgnotserver
  name: pgnotserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgnotserver
    spec:
      restartPolicy: Always
      volumes:
      - name: notserverdb
        persistentVolumeClaim:
          claimName: notserverdb
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFSERVER_PG_PASSWORD
        image: postgres:9.6.6
        name: pgnotserver
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: notserverdb
