---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pgnotserver
  name: notifserver-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: pgnotserver

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pgnotserver
  name: notifserver-db-pg
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pgnotserver
    spec:
      restartPolicy: Always
      volumes:
      - name: notserverdb
        persistentVolumeClaim:
          claimName: notserverdb
      containers:
      - image: postgres:9.6.6
        name: pgnotserver
        resources:
          requests:
            memory: "100Mi"
            cpu: "30m"
          limits:
            memory: "250Mi"
            cpu: "60m"
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: NOTIFSERVER_PG_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: notserverdb
