---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redisnotserver
  name: notifserver-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redisnotserver
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redisnotserver
  name: redisnotserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redisnotserver
    spec:
      containers:
      - image: redis
        name: redisnotserver
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: notserverredisdb
      restartPolicy: Always
      volumes:
      - name: notserverredisdb
        persistentVolumeClaim:
          claimName: notserverredisdb
