---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis-offerserver
  name: offerserver-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-offerserver
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis-offerserver
  name: offerserver-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis-offerserver
    spec:
      restartPolicy: Always
      volumes:
      - name: offerserverdb
        persistentVolumeClaim:
          claimName: offerserverdb
      containers:
      - image: redis
        name: redis-offerserver
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
          limits:
            memory: "75Mi"
            cpu: "20m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: offerserverdb
