---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo-store
  name: storage-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongo-store
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo-store
  name: storage-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongo-store
    spec:
      restartPolicy: Always
      volumes:
      - name: mongostoredb
        persistentVolumeClaim:
          claimName: mongostoredb
      containers:
      - image: mongo:3.6
        name: mongo-store
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongostoredb
