---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: website-database
  name: website-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: pgwebsite
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pgwebsite
    spec:
      restartPolicy: Always
      volumes:
      - name: websitedb
        persistentVolumeClaim:
          claimName: websitedb
      containers:
      - image: postgres:9.6.6
        name: pgwebsite
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8scfg
              key: WEBSITE_PG_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: websitedb
